### ISSUE TITLE
Crear rama 'pablo'

### ISSUE THREAD

**Issue by aguadopd** [edwin0790/template_tf_elo#6]
Si creas una rama 'pablo', puedo ir actualizando mi rama ahí, con pull request. O la podes actualizar vos, haciendo pull. 
[Aquí](https://stackoverflow.com/questions/14383212/git-pulling-a-branch-from-another-repository) vi como hacer lo mismo con la tuya. Deberías:

```bash
# Añadís mi repositorio como remoto
git remote add aguadopd https://github.com/aguadopd/template_tf_elo/
# Actualizás
git fetch aguadopd
# Crear rama 'pablo' desde la rama 'pablo' del remoto 'aguadopd' y cambiar a ella simultáneamente
git checkout -b pablo aguadopd/pablo
```

**Comment by edwin0790** [comment]
hecho

**Comment by aguadopd** [comment]
@edwin0790 hacé un commit inicial de creación de la rama y pushealo. Si no, no se ve por acá.
